export const PEOPLE_UPDATE_LOADING = 'PEOPLE_UPDATE_LOADING';
export const PEOPLE_UPDATE_LIST = 'PEOPLE_UPDATE_LIST';
export const PEOPLE_UPDATE_OFFSET = 'PEOPLE_UPDATE_OFFSET';
export const PEOPLE_UPDATE_ITEM = 'PEOPLE_UPDATE_ITEM';
